### ISSUE TITLE
Engines

### ISSUE THREAD

**Issue by FilipVavera** [cdriscol/policy-control#9]
Is the engines config really required for package to run?
https://github.com/cdriscol/policy-control/blob/master/package.json#L11

I am on `node 14.3.0` and `yarn 1.19.1` (because of the [bug](https://github.com/yarnpkg/yarn/issues/7734) in later yarn versions) and because of that I am unable to install this package without `--ignore-engines` flag.

**Comment by cdriscol** [comment]
@FilipVavera - engines config is good to have but I have it too constrained right now in the package.json. I can change to support node >= 12.x and remove the yarn check.

**Comment by cdriscol** [comment]
I pushed up v0.0.8 to add support for node >= 12 and removed yarn check - if you upgrade your dependency this should be resolved.  feel free to re-open or add a new issue if you are still having issues.

thanks for contributing!

https://github.com/cdriscol/policy-control/commit/efaa715c7751310e1d273f454f2a30da104a5682

**Comment by FilipVavera** [comment]
Thanks for quick response!

Works as expected now :)
